apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-collector
  labels:
    app: metrics-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-collector
  template:
    metadata:
      labels:
        app: metrics-collector
    spec:
      serviceAccountName: type-aware-scheduler
      containers:
      - name: metrics-collector
        image: pawelzell/metrics-collector
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: influxdb-creds

