apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-scheduler
  labels:
    app: random-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-scheduler
  template:
    metadata:
      labels:
        app: random-scheduler
    spec:
      serviceAccountName: type-aware-scheduler
      containers:
      - name: random-scheduler
        image: pawelzell/type-aware-scheduler
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: influxdb-creds
        env:
        - name: SCHEDULER_TYPE
          value: "random-scheduler"
