apiVersion: apps/v1
kind: Deployment
metadata:
  name: type-aware-scheduler
  labels:
    app: type-aware-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: type-aware-scheduler
  template:
    metadata:
      labels:
        app: type-aware-scheduler
    spec:
      serviceAccountName: type-aware-scheduler
      containers:
      - name: type-aware-scheduler
        image: pawelzell/type-aware-scheduler
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: influxdb-creds

