apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: influxdb
    project: type-aware-scheduler
  name: influxdb
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
