apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs: 
    server: 10.2.1.91
    path: /mnt/k8s-type-aware-scheduler-dosa/influxdb
#  hostPath:
#path: "/data/kube/pv1"

