apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs: 
    server: 127.0.0.1
    path: /mnt/k8s-type-aware-scheduler-kulcha/influxdb
#  hostPath:
#path: "/data/kube/pv1"

